### ISSUE TITLE
R-script run give error at 1rst compound building block (Rifampicin)

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/Database-for-observed-data#34] opened 2021-10-01 16:28 UTC
After including pediatric qualification related drug-datasets, i runned the r-script to generate data-building blocks, however at the first drug it already crashes, which is Rifampicin.

I dont know if this is a script bug, or dataset error! Please fix asap.

Message:

```
Error in getOrgan(studies$Compartment[SELECT_study], eachID) : 
  Unknown Compartment: Duodenum|Intracellular for 1358 
4.
stop("Unknown Compartment: ", compartment, " for ", eachID) at auxiliaryFunctions.R#229
3.
getOrgan(studies$Compartment[SELECT_study], eachID) 
2.
matrix(c("DB Version", "OSP DATABASE", "ID", as.character(studies$ID[SELECT_study]), 
    "Study Id", studies$Study[SELECT_study], "Reference", as.character(studies$Reference[SELECT_study]), 
    "Source", studies$Source[SELECT_study], "Grouping", studies$Grouping[SELECT_study], 
    "Data type", dataType, "N", ifelse(as.character(studies$N[SELECT_study]) !=  ... 
1.
as.data.frame(matrix(c("DB Version", "OSP DATABASE", "ID", as.character(studies$ID[SELECT_study]), 
    "Study Id", studies$Study[SELECT_study], "Reference", as.character(studies$Reference[SELECT_study]), 
    "Source", studies$Source[SELECT_study], "Grouping", studies$Grouping[SELECT_study], 
    "Data type", dataType, "N", ifelse(as.character(studies$N[SELECT_study]) !=  ... 
```

**Comment by Incei** [comment] 2021-10-03 10:40
FYI, i runned the r-script to generate data-building blocks **only for the pediatrics related drugs** (by selecting only these, via the Projects tab, without any errors.

**Comment by sfrechen** [comment] 2021-10-04 07:51
@Yuri05 @Incei 
Cannot reproduce. No errors  appear.
Tested using the database of the current commit (https://github.com/Open-Systems-Pharmacology/Database-for-observed-data/commit/bdeb0dc95dadbcb8b8d7375616c55c842bb78754) and the PR (https://github.com/Open-Systems-Pharmacology/Database-for-observed-data/pull/33).

Did you use the latest version of the scripts? `auxiliaryFunctions.R` got an update 5 month ago.

Here is my R console output:

```
source("C:/OSP/OSP/Database-for-observed-data/code/convert_XLS_to_JSON.R")
Writing:  ObsData_Rifampicin.json 
Writing:  ObsData_Midazolam.json 
Writing:  ObsData_Itraconazole-Midazolam-DDI.json 
Writing:  ObsData_Rifampicin-Midazolam-DDI.json 
Writing:  ObsData_Buspirone.json 
Writing:  ObsData_Itraconazole.json 
Writing:  ObsData_Ketoconazole-Midazolam-DDI.json 
Writing:  ObsData_Simvastatin.json 
Writing:  ObsData_Caffeine.json 
Writing:  ObsData_Atazanavir.json 
Writing:  ObsData_Clarithromycin-Midazolam-DDI.json 
Writing:  ObsData_Digoxin.json 
Writing:  ObsData_Rifampicin-Digoxin-DDI.json 
Writing:  ObsData_Clarithromycin-Digoxin-DDI.json 
Writing:  ObsData_Itraconazole-Digoxin-DDI.json 
Writing:  ObsData_Alfentanil.json 
Writing:  ObsData_Rifampicin-Alfentanil-DDI.json 
Writing:  ObsData_Erythromycin-Buspirone-DDI.json 
Writing:  ObsData_Erythromycin.json 
Writing:  ObsData_Itraconazole-Buspirone-DDI.json 
Writing:  ObsData_Fluvoxamine-Buspirone-DDI.json 
Writing:  ObsData_Rifampicin-Buspirone-DDI.json 
Writing:  ObsData_Verapamil-Buspirone-DDI.json 
Writing:  ObsData_Diltiazem-Buspirone-DDI.json 
Writing:  ObsData_Ketoconazole-Digoxin-DDI.json 
Writing:  ObsData_Erythromycin-Midazolam-DDI.json 
Writing:  ObsData_Ketoconazole.json 
Writing:  ObsData_Fluconazole-Midazolam-DDI.json 
Writing:  ObsData_Voriconazole-Midazolam-DDI.json 
Writing:  ObsData_Voriconazole.json 
Writing:  ObsData_Mefenamic acid.json 
Writing:  ObsData_Raltegravir.json 
Writing:  ObsData_Atazanavir-Raltegravir-DDI.json 
Writing:  ObsData_Dapagliflozin.json 
Writing:  ObsData_Rifampicin-Dapagliflozin-DDI.json 
Writing:  ObsData_Mefenamic acid-Dapagliflozin-DDI.json 
Writing:  ObsData_Triazolam.json 
Writing:  ObsData_Fluconazole-Triazolam-DDI.json 
Writing:  ObsData_Rifampicin-Triazolam-DDI.json 
Writing:  ObsData_Alprazolam.json 
Writing:  ObsData_Ketoconzaole-Alprazolam-DDI.json 
Writing:  ObsData_Rifampicin-Alprazolam-DDI.json 
Writing:  ObsData_Erythromycin-Triazolam-DDI.json 
Writing:  ObsData_Ketoconazole-Alfentanil-DDI.json 
Writing:  ObsData_Erythromycin-Alprazolam-DDI.json 
Writing:  ObsData_Erythromycin-Alfentanil-DDI.json 
Writing:  ObsData_Efavirenz.json 
Writing:  ObsData_Efavirenz-Alfentanil-DDI.json 
Writing:  ObsData_Ketoconazole-Alprazolam-DDI.json 
Writing:  ObsData_Itraconazole-Alprazolam-DDI.json 
Writing:  ObsData_Itraconazole-Triazolam-DDI.json 
Writing:  ObsData_Ketoconazole-Triazolam-DDI.json 
Writing:  ObsData_Fluvoxamine-Midazolam-DDI.json 
Writing:  ObsData_Rifampicin-Midazolam DDI.json 
Writing:  ObsData_Clarithromycin-Triazolam-DDI.json 
Writing:  ObsData_Fluvoxamine-Alprazolam-DDI.json 
Writing:  ObsData_Verapamil-Midazolam-DDI.json 
Writing:  ObsData_Verapamil.json 
Writing:  ObsData_Clarithromycin.json 
Writing:  ObsData_Efavirenz-Midazolam-DDI.json 
Writing:  ObsData_Rifampicin-Verapamil-DDI.json 
Writing:  ObsData_Cimetidine.json 
Writing:  ObsData_Cimetidine-Midazolam-DDI.json 
Writing:  ObsData_Cimetidine-Verapamil-DDI.json 
Writing:  ObsData_Cimetidine-Alprazolam-DDI.json 
Writing:  ObsData_Cimetidine-Triazolam-DDI.json 
Writing:  ObsData_Cimetidine-Alfentanil-DDI.json 
Writing:  ObsData_Pravastatin.json 
Writing:  ObsData_Pravastatin-Itraconazole-DDI.json 
Writing:  ObsData_Pravastatin-Fluconazole-DDI.json 
Writing:  ObsData_Pravastatin-Nelfinavir-DDI.json 
Writing:  ObsData_Pravastatin-Rifampicin-DDI.json 
Writing:  ObsData_Pravastatin-Diltiazem-DDI.json 
Writing:  ObsData_Pravastatin-Verapamil-DDI.json 
Writing:  ObsData_Pravastatin-Clarithromycin-DDI.json 
Writing:  ObsData_Pravastatin-Cyclosporin-DDI.json 
Writing:  ObsData_Pravastatin-Amiodarone-DDI.json 
Writing:  ObsData_Pravastatin-Gemfibrozil-DDI.json 
Writing:  ObsData_Fluconazole.json 
Writing:  ObsData_Fluconazole-Alfentanil-DDI.json 
Writing:  ObsData_Carbamazepine.json 
Writing:  ObsData_Amikacin.json 
Writing:  ObsData_Vancomycin.json 
Writing:  ObsData_Vancomycin-Pediatrics.json 
Writing:  ObsData_Alfentanil-Pediatrics.json 
Writing:  ObsData_Sufentanil.json 
Writing:  ObsData_Sufentanil-Pediatrics.json 
Writing:  ObsData_Montelukast-Pediatrics.json 
Writing:  ObsData_Montelukast.json 
Writing:  ObsData_Raltegravir-Pediatrics.json 
Writing:  ObsData_ALL.json 
There were 50 or more warnings (use warnings() to see the first 50)
```

**Comment by sfrechen** [comment] 2021-10-05 07:14
@Incei 
Can we close this issue? Can you still reproduce?

**Comment by Incei** [comment] 2021-10-05 07:17
I missed the email, srry, yes we can close!

**Closed** 2021-10-05 07:17 UTC
Labels: bug
